### ISSUE TITLE
Assertion failed: `'vault::crank_vault_update_state_tracker::tests::test_crank_vault_update_state_tracker_same_index_twice_fails`

### ISSUE THREAD

**Issue by aoikurokawa** [jito-foundation/restaking#51]
When I run ` cargo nextest run --all-features`, sometimes, test fails at `vault::crank_vault_update_state_tracker::tests::test_crank_vault_update_state_tracker_same_index_twice_fails`.

```bash
thread 'vault::crank_vault_update_state_tracker::tests::test_crank_vault_update_state_tracker_same_index_twice_fails' panicked at integration_tests/tests/vault/crank_vault_update_state_tracker.rs:289:9:
assertion `left == right` failed
  left: AlreadyProcessed
 right: InstructionError(0, Custom(2020))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Environment:
OS: Ubuntu 22.04.4 LTS
rustc: rustc 1.80.0 (051478957 2024-07-21)

**Comment by buffalu** [comment]
there needs to be a fixture.warp_to_slot call with 1 so there's a new blockhash

**Comment by aoikurokawa** [comment]
Since #52 merged, the problem is fixed
